# Generated by Django 4.1.5 on 2023-01-20 05:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('license_plate', models.CharField(help_text='Формат: X000XX00 или X000XX000', max_length=9, unique=True, validators=[django.core.validators.RegexValidator('/^[АВЕКМНОРСТУХ]\\d{3}(?<!000)[АВЕКМНОРСТУХ]{2}\\d{2,3}$/ui')])),
                ('body_type', models.CharField(choices=[('Estate', 'Универсал'), ('Hatchback', 'Хэтчбек'), ('Pickup', 'Пикап'), ('Sedan', 'Седан'), ('Crossover Utility Vehicle (CUV)', 'Кроссовер')], max_length=64)),
                ('color', models.CharField(choices=[('Gray', 'Серый'), ('Black', 'Чёрный'), ('White', 'Белый'), ('Blue', 'Синий'), ('Mixed', 'Смешанный')], max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
