# Generated by Django 4.1.5 on 2023-01-26 05:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(help_text='Формат: X000XX или X000XX', max_length=6, unique=True, validators=[django.core.validators.RegexValidator('[АВЕКМНОРСТУХ]\\d{3}(?!000)[АВЕКМНОРСТУХ]{2}')]),
        ),
    ]
